apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemeshcontrolplanes.maistra.io
spec:
  group: maistra.io
  names:
    kind: ServiceMeshControlPlane
    listKind: ServiceMeshControlPlaneList
    plural: servicemeshcontrolplanes
    singular: servicemeshcontrolplane
    shortNames:
    - smcp
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  additionalPrinterColumns:
  - name: Ready
    description: How many of the total number of member namespaces are
      configured
    type: string
    JSONPath: '.status.annotations.readyComponentCount'
  - JSONPath: .status.conditions[?(@.type=="Ready")].reason
    name: Status
    description: Whether or not the control plane installation is up to date and ready
      to handle requests.
    type: string
  - name: Template
    description: The configuration template to use as the base.
    type: string
    JSONPath: .status.lastAppliedConfiguration.template
  - name: Version
    description: The actual current version of the control plane installation.
    type: string
    JSONPath: .status.lastAppliedConfiguration.version
  - name: Age
    description: The age of the object
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Image HUB
    description: The image hub used as the base for all component images.
    type: string
    priority: 1
    JSONPath: .status.lastAppliedConfiguration.istio.global.hub
