apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: servicemeshmembers.maistra.io
spec:
  group: maistra.io
  names:
    kind: ServiceMeshMember
    listKind: ServiceMeshMemberList
    plural: servicemeshmembers
    singular: servicemeshmember
    shortNames:
    - smm
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  additionalPrinterColumns:
  - name: Control Plane Namespace
    description: The ServiceMeshControlPlane's namespace that this namespace belongs
      to
    type: string
    JSONPath: .spec.controlPlaneRef.namespace
  - name: Control Plane
    description: The ServiceMeshControlPlane that this namespace belongs to
    type: string
    JSONPath: .spec.controlPlaneRef.name
  - name: Ready
    description: Whether or not namespace is configured as a member of the mesh.
    type: string
    JSONPath: .status.conditions[?(@.type=="Ready")].status
