apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-sidecar-webhook-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "sidecar-injector.name" . }}
    chart: {{ template "sidecar-injector.chart" . }}
    heritage: {{ .Release.Service }}
    maistra-version: 1.0.5
    release: {{ .Release.Name }}
    istio: sidecar-injector
data:
  mutatingwebhookconfiguration.yaml: |-
    {{- include "mutatingwebhookconfiguration.yaml.tpl" . | indent 4}}
