apiVersion: v1
kind: Service
metadata:
  name: istio-sidecar-injector
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "sidecar-injector.name" . }}
    chart: {{ template "sidecar-injector.chart" . }}
    heritage: {{ .Release.Service }}
    maistra-version: 1.0.8
    release: {{ .Release.Name }}
    istio: sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: webhook
  selector:
    istio: sidecar-injector
