{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
{{- if and ($gateway.enabled) (eq $gateway.name "istio-ingressgateway") }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: istio-ingressgateway
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    {{- range $key, $val := $gateway.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  to:
    kind: Service
    name: istio-ingressgateway
  port:
    targetPort: 8080
{{- end }}
