{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
{{- if and ($gateway.enabled) (eq $gateway.name "istio-ingressgateway") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-ingressgateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ index .Values "gateways" "istio-ingressgateway" "labels" "istio" }}
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  podSelector:
    matchLabels:
      istio: ingressgateway
  ingress:
  - {}
{{- end }}
