{{- if and .Values.global.multitenant (index .Values "istio-ingressgateway" "enabled") }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-ingressgateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ index .Values "istio-ingressgateway" "labels" "istio" }}
    chart: {{ template "gateway.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  podSelector:
    matchLabels:
      istio: ingressgateway
  ingress:
  - from:
    - namespaceSelector: {}

{{- end }}
