apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: minimal
spec:
  tracing:
    # change to Jaeger to enable tracing
    type: None
  techPreview:
    wasmExtensions:
      enabled: true
  addons:
    jaeger:
      name: jaeger
      install: {}
    grafana:
      enabled: false
      install: {}
    kiali:
      name: kiali
      enabled: false
      install: {}

---

apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
spec:
  members:
  - test
  # a list of namespaces that should be joined into the service mesh
  # for example, to add the bookinfo namespace
  #- bookinfo
