{{- if and (.Values.enabled) (index .Values "istio-ingressgateway" "enabled") (index .Values "istio-ingressgateway" "ior_enabled") }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ior
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: 1.2.0
    app: ior
    chart: {{ template "gateway.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes", "routes/custom-host"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list"]
{{- end }}
