kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: servicemeshrbacconfigs.rbac.maistra.io
  labels:
    app: istio-pilot
    istio: rbac
    heritage: Tiller
    maistra-version: 1.0.11
    release: istio
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: rbac.maistra.io
  names:
    kind: ServiceMeshRbacConfig
    plural: servicemeshrbacconfigs
    singular: servicemeshrbacconfig
    categories:
    - istio-io
    - rbac-istio-io
  scope: Namespaced
  version: v1