apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      containers:
        - name: istio-operator
          image: maistra/istio-operator-centos7:0.9.0
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - istio-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "istio-operator"
