//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"encoding/json"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArchConfig) DeepCopyInto(out *ArchConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArchConfig.
func (in *ArchConfig) DeepCopy() *ArchConfig {
	if in == nil {
		return nil
	}
	out := new(ArchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseConfig) DeepCopyInto(out *BaseConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseConfig.
func (in *BaseConfig) DeepCopy() *BaseConfig {
	if in == nil {
		return nil
	}
	out := new(BaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CA) DeepCopyInto(out *CA) {
	*out = *in
	if in.TLSSettings != nil {
		in, out := &in.TLSSettings, &out.TLSSettings
		*out = new(ClientTLSSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CA.
func (in *CA) DeepCopy() *CA {
	if in == nil {
		return nil
	}
	out := new(CA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIAmbientConfig) DeepCopyInto(out *CNIAmbientConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIAmbientConfig.
func (in *CNIAmbientConfig) DeepCopy() *CNIAmbientConfig {
	if in == nil {
		return nil
	}
	out := new(CNIAmbientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIConfig) DeepCopyInto(out *CNIConfig) {
	*out = *in
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.Repair != nil {
		in, out := &in.Repair, &out.Repair
		*out = new(CNIRepairConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceQuotas != nil {
		in, out := &in.ResourceQuotas, &out.ResourceQuotas
		*out = new(ResourceQuotas)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(Resources)
		(*in).DeepCopyInto(*out)
	}
	if in.SeccompProfile != nil {
		in, out := &in.SeccompProfile, &out.SeccompProfile
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Ambient != nil {
		in, out := &in.Ambient, &out.Ambient
		*out = new(CNIAmbientConfig)
		**out = **in
	}
	if in.RollingMaxUnavailable != nil {
		in, out := &in.RollingMaxUnavailable, &out.RollingMaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIConfig.
func (in *CNIConfig) DeepCopy() *CNIConfig {
	if in == nil {
		return nil
	}
	out := new(CNIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIRepairConfig) DeepCopyInto(out *CNIRepairConfig) {
	*out = *in
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIRepairConfig.
func (in *CNIRepairConfig) DeepCopy() *CNIRepairConfig {
	if in == nil {
		return nil
	}
	out := new(CNIRepairConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateData) DeepCopyInto(out *CertificateData) {
	*out = *in
	if in.CertSigners != nil {
		in, out := &in.CertSigners, &out.CertSigners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TrustDomains != nil {
		in, out := &in.TrustDomains, &out.TrustDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateData.
func (in *CertificateData) DeepCopy() *CertificateData {
	if in == nil {
		return nil
	}
	out := new(CertificateData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientTLSSettings) DeepCopyInto(out *ClientTLSSettings) {
	*out = *in
	if in.SubjectAltNames != nil {
		in, out := &in.SubjectAltNames, &out.SubjectAltNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientTLSSettings.
func (in *ClientTLSSettings) DeepCopy() *ClientTLSSettings {
	if in == nil {
		return nil
	}
	out := new(ClientTLSSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSource) DeepCopyInto(out *ConfigSource) {
	*out = *in
	if in.TLSSettings != nil {
		in, out := &in.TLSSettings, &out.TLSSettings
		*out = new(ClientTLSSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.SubscribedResources != nil {
		in, out := &in.SubscribedResources, &out.SubscribedResources
		*out = make([]Resource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSource.
func (in *ConfigSource) DeepCopy() *ConfigSource {
	if in == nil {
		return nil
	}
	out := new(ConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionPoolSettingsTCPSettingsTCPKeepalive) DeepCopyInto(out *ConnectionPoolSettingsTCPSettingsTCPKeepalive) {
	*out = *in
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionPoolSettingsTCPSettingsTCPKeepalive.
func (in *ConnectionPoolSettingsTCPSettingsTCPKeepalive) DeepCopy() *ConnectionPoolSettingsTCPSettingsTCPKeepalive {
	if in == nil {
		return nil
	}
	out := new(ConnectionPoolSettingsTCPSettingsTCPKeepalive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPodDisruptionBudgetConfig) DeepCopyInto(out *DefaultPodDisruptionBudgetConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPodDisruptionBudgetConfig.
func (in *DefaultPodDisruptionBudgetConfig) DeepCopy() *DefaultPodDisruptionBudgetConfig {
	if in == nil {
		return nil
	}
	out := new(DefaultPodDisruptionBudgetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultProviders) DeepCopyInto(out *DefaultProviders) {
	*out = *in
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AccessLogging != nil {
		in, out := &in.AccessLogging, &out.AccessLogging
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultProviders.
func (in *DefaultProviders) DeepCopy() *DefaultProviders {
	if in == nil {
		return nil
	}
	out := new(DefaultProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultResourcesConfig) DeepCopyInto(out *DefaultResourcesConfig) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(ResourcesRequestsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultResourcesConfig.
func (in *DefaultResourcesConfig) DeepCopy() *DefaultResourcesConfig {
	if in == nil {
		return nil
	}
	out := new(DefaultResourcesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressGatewayConfig) DeepCopyInto(out *EgressGatewayConfig) {
	*out = *in
	in.Env.DeepCopyInto(&out.Env)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*PortsConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PortsConfig)
				**out = **in
			}
		}
	}
	if in.SecretVolumes != nil {
		in, out := &in.SecretVolumes, &out.SecretVolumes
		*out = make([]*SecretVolume, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SecretVolume)
				**out = **in
			}
		}
	}
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Zvpn != nil {
		in, out := &in.Zvpn, &out.Zvpn
		*out = new(ZeroVPNConfig)
		**out = **in
	}
	in.ConfigVolumes.DeepCopyInto(&out.ConfigVolumes)
	if in.AdditionalContainers != nil {
		in, out := &in.AdditionalContainers, &out.AdditionalContainers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(ServiceAccount)
		(*in).DeepCopyInto(*out)
	}
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressGatewayConfig.
func (in *EgressGatewayConfig) DeepCopy() *EgressGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(EgressGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProvider) DeepCopyInto(out *ExtensionProvider) {
	*out = *in
	if in.EnvoyExtAuthzHTTP != nil {
		in, out := &in.EnvoyExtAuthzHTTP, &out.EnvoyExtAuthzHTTP
		*out = new(ExtensionProviderEnvoyExternalAuthorizationHTTPProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvoyExtAuthzGrpc != nil {
		in, out := &in.EnvoyExtAuthzGrpc, &out.EnvoyExtAuthzGrpc
		*out = new(ExtensionProviderEnvoyExternalAuthorizationGrpcProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Zipkin != nil {
		in, out := &in.Zipkin, &out.Zipkin
		*out = new(ExtensionProviderZipkinTracingProvider)
		**out = **in
	}
	if in.Datadog != nil {
		in, out := &in.Datadog, &out.Datadog
		*out = new(ExtensionProviderDatadogTracingProvider)
		**out = **in
	}
	if in.Stackdriver != nil {
		in, out := &in.Stackdriver, &out.Stackdriver
		*out = new(ExtensionProviderStackdriverProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Skywalking != nil {
		in, out := &in.Skywalking, &out.Skywalking
		*out = new(ExtensionProviderSkyWalkingTracingProvider)
		**out = **in
	}
	if in.Opentelemetry != nil {
		in, out := &in.Opentelemetry, &out.Opentelemetry
		*out = new(ExtensionProviderOpenTelemetryTracingProvider)
		**out = **in
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(ExtensionProviderPrometheusMetricsProvider)
		**out = **in
	}
	if in.EnvoyFileAccessLog != nil {
		in, out := &in.EnvoyFileAccessLog, &out.EnvoyFileAccessLog
		*out = new(ExtensionProviderEnvoyFileAccessLogProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvoyHTTPAls != nil {
		in, out := &in.EnvoyHTTPAls, &out.EnvoyHTTPAls
		*out = new(ExtensionProviderEnvoyHTTPGrpcV3LogProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvoyTCPAls != nil {
		in, out := &in.EnvoyTCPAls, &out.EnvoyTCPAls
		*out = new(ExtensionProviderEnvoyTCPGrpcV3LogProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvoyOtelAls != nil {
		in, out := &in.EnvoyOtelAls, &out.EnvoyOtelAls
		*out = new(ExtensionProviderEnvoyOpenTelemetryLogProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProvider.
func (in *ExtensionProvider) DeepCopy() *ExtensionProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderDatadogTracingProvider) DeepCopyInto(out *ExtensionProviderDatadogTracingProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderDatadogTracingProvider.
func (in *ExtensionProviderDatadogTracingProvider) DeepCopy() *ExtensionProviderDatadogTracingProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderDatadogTracingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderEnvoyExternalAuthorizationGrpcProvider) DeepCopyInto(out *ExtensionProviderEnvoyExternalAuthorizationGrpcProvider) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.IncludeRequestBodyInCheck != nil {
		in, out := &in.IncludeRequestBodyInCheck, &out.IncludeRequestBodyInCheck
		*out = new(ExtensionProviderEnvoyExternalAuthorizationRequestBody)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderEnvoyExternalAuthorizationGrpcProvider.
func (in *ExtensionProviderEnvoyExternalAuthorizationGrpcProvider) DeepCopy() *ExtensionProviderEnvoyExternalAuthorizationGrpcProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderEnvoyExternalAuthorizationGrpcProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderEnvoyExternalAuthorizationHTTPProvider) DeepCopyInto(out *ExtensionProviderEnvoyExternalAuthorizationHTTPProvider) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.IncludeRequestHeadersInCheck != nil {
		in, out := &in.IncludeRequestHeadersInCheck, &out.IncludeRequestHeadersInCheck
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeAdditionalHeadersInCheck != nil {
		in, out := &in.IncludeAdditionalHeadersInCheck, &out.IncludeAdditionalHeadersInCheck
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IncludeRequestBodyInCheck != nil {
		in, out := &in.IncludeRequestBodyInCheck, &out.IncludeRequestBodyInCheck
		*out = new(ExtensionProviderEnvoyExternalAuthorizationRequestBody)
		**out = **in
	}
	if in.HeadersToUpstreamOnAllow != nil {
		in, out := &in.HeadersToUpstreamOnAllow, &out.HeadersToUpstreamOnAllow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HeadersToDownstreamOnDeny != nil {
		in, out := &in.HeadersToDownstreamOnDeny, &out.HeadersToDownstreamOnDeny
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HeadersToDownstreamOnAllow != nil {
		in, out := &in.HeadersToDownstreamOnAllow, &out.HeadersToDownstreamOnAllow
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderEnvoyExternalAuthorizationHTTPProvider.
func (in *ExtensionProviderEnvoyExternalAuthorizationHTTPProvider) DeepCopy() *ExtensionProviderEnvoyExternalAuthorizationHTTPProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderEnvoyExternalAuthorizationHTTPProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderEnvoyExternalAuthorizationRequestBody) DeepCopyInto(out *ExtensionProviderEnvoyExternalAuthorizationRequestBody) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderEnvoyExternalAuthorizationRequestBody.
func (in *ExtensionProviderEnvoyExternalAuthorizationRequestBody) DeepCopy() *ExtensionProviderEnvoyExternalAuthorizationRequestBody {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderEnvoyExternalAuthorizationRequestBody)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderEnvoyFileAccessLogProvider) DeepCopyInto(out *ExtensionProviderEnvoyFileAccessLogProvider) {
	*out = *in
	if in.LogFormat != nil {
		in, out := &in.LogFormat, &out.LogFormat
		*out = new(ExtensionProviderEnvoyFileAccessLogProviderLogFormat)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderEnvoyFileAccessLogProvider.
func (in *ExtensionProviderEnvoyFileAccessLogProvider) DeepCopy() *ExtensionProviderEnvoyFileAccessLogProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderEnvoyFileAccessLogProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderEnvoyFileAccessLogProviderLogFormat) DeepCopyInto(out *ExtensionProviderEnvoyFileAccessLogProviderLogFormat) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderEnvoyFileAccessLogProviderLogFormat.
func (in *ExtensionProviderEnvoyFileAccessLogProviderLogFormat) DeepCopy() *ExtensionProviderEnvoyFileAccessLogProviderLogFormat {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderEnvoyFileAccessLogProviderLogFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderEnvoyHTTPGrpcV3LogProvider) DeepCopyInto(out *ExtensionProviderEnvoyHTTPGrpcV3LogProvider) {
	*out = *in
	if in.FilterStateObjectsToLog != nil {
		in, out := &in.FilterStateObjectsToLog, &out.FilterStateObjectsToLog
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalRequestHeadersToLog != nil {
		in, out := &in.AdditionalRequestHeadersToLog, &out.AdditionalRequestHeadersToLog
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalResponseHeadersToLog != nil {
		in, out := &in.AdditionalResponseHeadersToLog, &out.AdditionalResponseHeadersToLog
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalResponseTrailersToLog != nil {
		in, out := &in.AdditionalResponseTrailersToLog, &out.AdditionalResponseTrailersToLog
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderEnvoyHTTPGrpcV3LogProvider.
func (in *ExtensionProviderEnvoyHTTPGrpcV3LogProvider) DeepCopy() *ExtensionProviderEnvoyHTTPGrpcV3LogProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderEnvoyHTTPGrpcV3LogProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderEnvoyOpenTelemetryLogProvider) DeepCopyInto(out *ExtensionProviderEnvoyOpenTelemetryLogProvider) {
	*out = *in
	if in.LogFormat != nil {
		in, out := &in.LogFormat, &out.LogFormat
		*out = new(ExtensionProviderEnvoyOpenTelemetryLogProviderLogFormat)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderEnvoyOpenTelemetryLogProvider.
func (in *ExtensionProviderEnvoyOpenTelemetryLogProvider) DeepCopy() *ExtensionProviderEnvoyOpenTelemetryLogProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderEnvoyOpenTelemetryLogProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderEnvoyOpenTelemetryLogProviderLogFormat) DeepCopyInto(out *ExtensionProviderEnvoyOpenTelemetryLogProviderLogFormat) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderEnvoyOpenTelemetryLogProviderLogFormat.
func (in *ExtensionProviderEnvoyOpenTelemetryLogProviderLogFormat) DeepCopy() *ExtensionProviderEnvoyOpenTelemetryLogProviderLogFormat {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderEnvoyOpenTelemetryLogProviderLogFormat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderEnvoyTCPGrpcV3LogProvider) DeepCopyInto(out *ExtensionProviderEnvoyTCPGrpcV3LogProvider) {
	*out = *in
	if in.FilterStateObjectsToLog != nil {
		in, out := &in.FilterStateObjectsToLog, &out.FilterStateObjectsToLog
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderEnvoyTCPGrpcV3LogProvider.
func (in *ExtensionProviderEnvoyTCPGrpcV3LogProvider) DeepCopy() *ExtensionProviderEnvoyTCPGrpcV3LogProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderEnvoyTCPGrpcV3LogProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderLightstepTracingProvider) DeepCopyInto(out *ExtensionProviderLightstepTracingProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderLightstepTracingProvider.
func (in *ExtensionProviderLightstepTracingProvider) DeepCopy() *ExtensionProviderLightstepTracingProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderLightstepTracingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderOpenCensusAgentTracingProvider) DeepCopyInto(out *ExtensionProviderOpenCensusAgentTracingProvider) {
	*out = *in
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = make([]ExtensionProviderOpenCensusAgentTracingProviderTraceContext, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderOpenCensusAgentTracingProvider.
func (in *ExtensionProviderOpenCensusAgentTracingProvider) DeepCopy() *ExtensionProviderOpenCensusAgentTracingProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderOpenCensusAgentTracingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderOpenTelemetryTracingProvider) DeepCopyInto(out *ExtensionProviderOpenTelemetryTracingProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderOpenTelemetryTracingProvider.
func (in *ExtensionProviderOpenTelemetryTracingProvider) DeepCopy() *ExtensionProviderOpenTelemetryTracingProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderOpenTelemetryTracingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderPrometheusMetricsProvider) DeepCopyInto(out *ExtensionProviderPrometheusMetricsProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderPrometheusMetricsProvider.
func (in *ExtensionProviderPrometheusMetricsProvider) DeepCopy() *ExtensionProviderPrometheusMetricsProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderPrometheusMetricsProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderSkyWalkingTracingProvider) DeepCopyInto(out *ExtensionProviderSkyWalkingTracingProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderSkyWalkingTracingProvider.
func (in *ExtensionProviderSkyWalkingTracingProvider) DeepCopy() *ExtensionProviderSkyWalkingTracingProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderSkyWalkingTracingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderStackdriverProvider) DeepCopyInto(out *ExtensionProviderStackdriverProvider) {
	*out = *in
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(ExtensionProviderStackdriverProviderLogging)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderStackdriverProvider.
func (in *ExtensionProviderStackdriverProvider) DeepCopy() *ExtensionProviderStackdriverProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderStackdriverProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderStackdriverProviderLogging) DeepCopyInto(out *ExtensionProviderStackdriverProviderLogging) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderStackdriverProviderLogging.
func (in *ExtensionProviderStackdriverProviderLogging) DeepCopy() *ExtensionProviderStackdriverProviderLogging {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderStackdriverProviderLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionProviderZipkinTracingProvider) DeepCopyInto(out *ExtensionProviderZipkinTracingProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionProviderZipkinTracingProvider.
func (in *ExtensionProviderZipkinTracingProvider) DeepCopy() *ExtensionProviderZipkinTracingProvider {
	if in == nil {
		return nil
	}
	out := new(ExtensionProviderZipkinTracingProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaysConfig) DeepCopyInto(out *GatewaysConfig) {
	*out = *in
	if in.IstioEgressgateway != nil {
		in, out := &in.IstioEgressgateway, &out.IstioEgressgateway
		*out = new(EgressGatewayConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.IstioIngressgateway != nil {
		in, out := &in.IstioIngressgateway, &out.IstioIngressgateway
		*out = new(IngressGatewayConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaysConfig.
func (in *GatewaysConfig) DeepCopy() *GatewaysConfig {
	if in == nil {
		return nil
	}
	out := new(GatewaysConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalConfig) DeepCopyInto(out *GlobalConfig) {
	*out = *in
	if in.CertSigners != nil {
		in, out := &in.CertSigners, &out.CertSigners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultConfigVisibilitySettings != nil {
		in, out := &in.DefaultConfigVisibilitySettings, &out.DefaultConfigVisibilitySettings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(GlobalLoggingConfig)
		**out = **in
	}
	if in.MeshNetworks != nil {
		in, out := &in.MeshNetworks, &out.MeshNetworks
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MultiCluster != nil {
		in, out := &in.MultiCluster, &out.MultiCluster
		*out = new(MultiClusterConfig)
		**out = **in
	}
	if in.PodDNSSearchNamespaces != nil {
		in, out := &in.PodDNSSearchNamespaces, &out.PodDNSSearchNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ProxyInit != nil {
		in, out := &in.ProxyInit, &out.ProxyInit
		*out = new(ProxyInitConfig)
		**out = **in
	}
	if in.Sds != nil {
		in, out := &in.Sds, &out.Sds
		*out = new(SDSConfig)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Tracer != nil {
		in, out := &in.Tracer, &out.Tracer
		*out = new(TracerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Istiod != nil {
		in, out := &in.Istiod, &out.Istiod
		*out = new(IstiodConfig)
		**out = **in
	}
	if in.Sts != nil {
		in, out := &in.Sts, &out.Sts
		*out = new(STSConfig)
		**out = **in
	}
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalConfig.
func (in *GlobalConfig) DeepCopy() *GlobalConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalLoggingConfig) DeepCopyInto(out *GlobalLoggingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalLoggingConfig.
func (in *GlobalLoggingConfig) DeepCopy() *GlobalLoggingConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalLoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRetry) DeepCopyInto(out *HTTPRetry) {
	*out = *in
	if in.PerTryTimeout != nil {
		in, out := &in.PerTryTimeout, &out.PerTryTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRetry.
func (in *HTTPRetry) DeepCopy() *HTTPRetry {
	if in == nil {
		return nil
	}
	out := new(HTTPRetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressGatewayConfig) DeepCopyInto(out *IngressGatewayConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LoadBalancerSourceRanges != nil {
		in, out := &in.LoadBalancerSourceRanges, &out.LoadBalancerSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]*PortsConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(PortsConfig)
				**out = **in
			}
		}
	}
	if in.SecretVolumes != nil {
		in, out := &in.SecretVolumes, &out.SecretVolumes
		*out = make([]*SecretVolume, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SecretVolume)
				**out = **in
			}
		}
	}
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Zvpn != nil {
		in, out := &in.Zvpn, &out.Zvpn
		*out = new(IngressGatewayZvpnConfig)
		**out = **in
	}
	if in.IngressPorts != nil {
		in, out := &in.IngressPorts, &out.IngressPorts
		*out = make([]corev1.ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalContainers != nil {
		in, out := &in.AdditionalContainers, &out.AdditionalContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigVolumes != nil {
		in, out := &in.ConfigVolumes, &out.ConfigVolumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(ServiceAccount)
		(*in).DeepCopyInto(*out)
	}
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressGatewayConfig.
func (in *IngressGatewayConfig) DeepCopy() *IngressGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(IngressGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressGatewayZvpnConfig) DeepCopyInto(out *IngressGatewayZvpnConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressGatewayZvpnConfig.
func (in *IngressGatewayZvpnConfig) DeepCopy() *IngressGatewayZvpnConfig {
	if in == nil {
		return nil
	}
	out := new(IngressGatewayZvpnConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Istio) DeepCopyInto(out *Istio) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Istio.
func (in *Istio) DeepCopy() *Istio {
	if in == nil {
		return nil
	}
	out := new(Istio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Istio) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioCondition) DeepCopyInto(out *IstioCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioCondition.
func (in *IstioCondition) DeepCopy() *IstioCondition {
	if in == nil {
		return nil
	}
	out := new(IstioCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioList) DeepCopyInto(out *IstioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Istio, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioList.
func (in *IstioList) DeepCopy() *IstioList {
	if in == nil {
		return nil
	}
	out := new(IstioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IstioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioRevision) DeepCopyInto(out *IstioRevision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioRevision.
func (in *IstioRevision) DeepCopy() *IstioRevision {
	if in == nil {
		return nil
	}
	out := new(IstioRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IstioRevision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioRevisionCondition) DeepCopyInto(out *IstioRevisionCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioRevisionCondition.
func (in *IstioRevisionCondition) DeepCopy() *IstioRevisionCondition {
	if in == nil {
		return nil
	}
	out := new(IstioRevisionCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioRevisionList) DeepCopyInto(out *IstioRevisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IstioRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioRevisionList.
func (in *IstioRevisionList) DeepCopy() *IstioRevisionList {
	if in == nil {
		return nil
	}
	out := new(IstioRevisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IstioRevisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioRevisionSpec) DeepCopyInto(out *IstioRevisionSpec) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioRevisionSpec.
func (in *IstioRevisionSpec) DeepCopy() *IstioRevisionSpec {
	if in == nil {
		return nil
	}
	out := new(IstioRevisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioRevisionStatus) DeepCopyInto(out *IstioRevisionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]IstioRevisionCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioRevisionStatus.
func (in *IstioRevisionStatus) DeepCopy() *IstioRevisionStatus {
	if in == nil {
		return nil
	}
	out := new(IstioRevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioSpec) DeepCopyInto(out *IstioSpec) {
	*out = *in
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(IstioUpdateStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = new(Values)
		(*in).DeepCopyInto(*out)
	}
	if in.RawValues != nil {
		in, out := &in.RawValues, &out.RawValues
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioSpec.
func (in *IstioSpec) DeepCopy() *IstioSpec {
	if in == nil {
		return nil
	}
	out := new(IstioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioStatus) DeepCopyInto(out *IstioStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]IstioCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Revisions = in.Revisions
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioStatus.
func (in *IstioStatus) DeepCopy() *IstioStatus {
	if in == nil {
		return nil
	}
	out := new(IstioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioUpdateStrategy) DeepCopyInto(out *IstioUpdateStrategy) {
	*out = *in
	if in.InactiveRevisionDeletionGracePeriodSeconds != nil {
		in, out := &in.InactiveRevisionDeletionGracePeriodSeconds, &out.InactiveRevisionDeletionGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioUpdateStrategy.
func (in *IstioUpdateStrategy) DeepCopy() *IstioUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(IstioUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstiodConfig) DeepCopyInto(out *IstiodConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstiodConfig.
func (in *IstiodConfig) DeepCopy() *IstiodConfig {
	if in == nil {
		return nil
	}
	out := new(IstiodConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstiodRemoteConfig) DeepCopyInto(out *IstiodRemoteConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstiodRemoteConfig.
func (in *IstiodRemoteConfig) DeepCopy() *IstiodRemoteConfig {
	if in == nil {
		return nil
	}
	out := new(IstiodRemoteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalityLoadBalancerSetting) DeepCopyInto(out *LocalityLoadBalancerSetting) {
	*out = *in
	if in.Distribute != nil {
		in, out := &in.Distribute, &out.Distribute
		*out = make([]*LocalityLoadBalancerSettingDistribute, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(LocalityLoadBalancerSettingDistribute)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Failover != nil {
		in, out := &in.Failover, &out.Failover
		*out = make([]*LocalityLoadBalancerSettingFailover, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(LocalityLoadBalancerSettingFailover)
				**out = **in
			}
		}
	}
	if in.FailoverPriority != nil {
		in, out := &in.FailoverPriority, &out.FailoverPriority
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalityLoadBalancerSetting.
func (in *LocalityLoadBalancerSetting) DeepCopy() *LocalityLoadBalancerSetting {
	if in == nil {
		return nil
	}
	out := new(LocalityLoadBalancerSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalityLoadBalancerSettingDistribute) DeepCopyInto(out *LocalityLoadBalancerSettingDistribute) {
	*out = *in
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make(map[string]uint32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalityLoadBalancerSettingDistribute.
func (in *LocalityLoadBalancerSettingDistribute) DeepCopy() *LocalityLoadBalancerSettingDistribute {
	if in == nil {
		return nil
	}
	out := new(LocalityLoadBalancerSettingDistribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalityLoadBalancerSettingFailover) DeepCopyInto(out *LocalityLoadBalancerSettingFailover) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalityLoadBalancerSettingFailover.
func (in *LocalityLoadBalancerSettingFailover) DeepCopy() *LocalityLoadBalancerSettingFailover {
	if in == nil {
		return nil
	}
	out := new(LocalityLoadBalancerSettingFailover)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfig) DeepCopyInto(out *MeshConfig) {
	*out = *in
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.TCPKeepalive != nil {
		in, out := &in.TCPKeepalive, &out.TCPKeepalive
		*out = new(ConnectionPoolSettingsTCPSettingsTCPKeepalive)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultConfig != nil {
		in, out := &in.DefaultConfig, &out.DefaultConfig
		*out = new(ProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OutboundTrafficPolicy != nil {
		in, out := &in.OutboundTrafficPolicy, &out.OutboundTrafficPolicy
		*out = new(OutboundTrafficPolicy)
		**out = **in
	}
	if in.ConfigSources != nil {
		in, out := &in.ConfigSources, &out.ConfigSources
		*out = make([]*ConfigSource, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ConfigSource)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TrustDomainAliases != nil {
		in, out := &in.TrustDomainAliases, &out.TrustDomainAliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CaCertificates != nil {
		in, out := &in.CaCertificates, &out.CaCertificates
		*out = make([]*CertificateData, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CertificateData)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DefaultServiceExportTo != nil {
		in, out := &in.DefaultServiceExportTo, &out.DefaultServiceExportTo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultVirtualServiceExportTo != nil {
		in, out := &in.DefaultVirtualServiceExportTo, &out.DefaultVirtualServiceExportTo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultDestinationRuleExportTo != nil {
		in, out := &in.DefaultDestinationRuleExportTo, &out.DefaultDestinationRuleExportTo
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LocalityLbSetting != nil {
		in, out := &in.LocalityLbSetting, &out.LocalityLbSetting
		*out = new(LocalityLoadBalancerSetting)
		(*in).DeepCopyInto(*out)
	}
	if in.DNSRefreshRate != nil {
		in, out := &in.DNSRefreshRate, &out.DNSRefreshRate
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ExtensionProviders != nil {
		in, out := &in.ExtensionProviders, &out.ExtensionProviders
		*out = make([]*ExtensionProvider, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ExtensionProvider)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.DefaultProviders != nil {
		in, out := &in.DefaultProviders, &out.DefaultProviders
		*out = new(DefaultProviders)
		(*in).DeepCopyInto(*out)
	}
	if in.DiscoverySelectors != nil {
		in, out := &in.DiscoverySelectors, &out.DiscoverySelectors
		*out = make([]*v1.LabelSelector, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.LabelSelector)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.PathNormalization != nil {
		in, out := &in.PathNormalization, &out.PathNormalization
		*out = new(ProxyPathNormalization)
		**out = **in
	}
	if in.DefaultHTTPRetryPolicy != nil {
		in, out := &in.DefaultHTTPRetryPolicy, &out.DefaultHTTPRetryPolicy
		*out = new(HTTPRetry)
		(*in).DeepCopyInto(*out)
	}
	if in.MeshMTLS != nil {
		in, out := &in.MeshMTLS, &out.MeshMTLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSDefaults != nil {
		in, out := &in.TLSDefaults, &out.TLSDefaults
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfig.
func (in *MeshConfig) DeepCopy() *MeshConfig {
	if in == nil {
		return nil
	}
	out := new(MeshConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterConfig) DeepCopyInto(out *MultiClusterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterConfig.
func (in *MultiClusterConfig) DeepCopy() *MultiClusterConfig {
	if in == nil {
		return nil
	}
	out := new(MultiClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundTrafficPolicy) DeepCopyInto(out *OutboundTrafficPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundTrafficPolicy.
func (in *OutboundTrafficPolicy) DeepCopy() *OutboundTrafficPolicy {
	if in == nil {
		return nil
	}
	out := new(OutboundTrafficPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundTrafficPolicyConfig) DeepCopyInto(out *OutboundTrafficPolicyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundTrafficPolicyConfig.
func (in *OutboundTrafficPolicyConfig) DeepCopy() *OutboundTrafficPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(OutboundTrafficPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotConfig) DeepCopyInto(out *PilotConfig) {
	*out = *in
	if in.AutoscaleBehavior != nil {
		in, out := &in.AutoscaleBehavior, &out.AutoscaleBehavior
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeploymentLabels != nil {
		in, out := &in.DeploymentLabels, &out.DeploymentLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigSource != nil {
		in, out := &in.ConfigSource, &out.ConfigSource
		*out = new(PilotConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.SeccompProfile != nil {
		in, out := &in.SeccompProfile, &out.SeccompProfile
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtraContainerArgs != nil {
		in, out := &in.ExtraContainerArgs, &out.ExtraContainerArgs
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotConfig.
func (in *PilotConfig) DeepCopy() *PilotConfig {
	if in == nil {
		return nil
	}
	out := new(PilotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotConfigSource) DeepCopyInto(out *PilotConfigSource) {
	*out = *in
	if in.SubscribedResources != nil {
		in, out := &in.SubscribedResources, &out.SubscribedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotConfigSource.
func (in *PilotConfigSource) DeepCopy() *PilotConfigSource {
	if in == nil {
		return nil
	}
	out := new(PilotConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotIngressConfig) DeepCopyInto(out *PilotIngressConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotIngressConfig.
func (in *PilotIngressConfig) DeepCopy() *PilotIngressConfig {
	if in == nil {
		return nil
	}
	out := new(PilotIngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotPolicyConfig) DeepCopyInto(out *PilotPolicyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotPolicyConfig.
func (in *PilotPolicyConfig) DeepCopy() *PilotPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(PilotPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortsConfig) DeepCopyInto(out *PortsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortsConfig.
func (in *PortsConfig) DeepCopy() *PortsConfig {
	if in == nil {
		return nil
	}
	out := new(PortsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(StartupProbe)
		**out = **in
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyInitConfig) DeepCopyInto(out *ProxyInitConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyInitConfig.
func (in *ProxyInitConfig) DeepCopy() *ProxyInitConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyInitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyPathNormalization) DeepCopyInto(out *ProxyPathNormalization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyPathNormalization.
func (in *ProxyPathNormalization) DeepCopy() *ProxyPathNormalization {
	if in == nil {
		return nil
	}
	out := new(ProxyPathNormalization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotas) DeepCopyInto(out *ResourceQuotas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotas.
func (in *ResourceQuotas) DeepCopy() *ResourceQuotas {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesRequestsConfig) DeepCopyInto(out *ResourcesRequestsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesRequestsConfig.
func (in *ResourcesRequestsConfig) DeepCopy() *ResourcesRequestsConfig {
	if in == nil {
		return nil
	}
	out := new(ResourcesRequestsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionSummary) DeepCopyInto(out *RevisionSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionSummary.
func (in *RevisionSummary) DeepCopy() *RevisionSummary {
	if in == nil {
		return nil
	}
	out := new(RevisionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDSConfig) DeepCopyInto(out *SDSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDSConfig.
func (in *SDSConfig) DeepCopy() *SDSConfig {
	if in == nil {
		return nil
	}
	out := new(SDSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *STSConfig) DeepCopyInto(out *STSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new STSConfig.
func (in *STSConfig) DeepCopy() *STSConfig {
	if in == nil {
		return nil
	}
	out := new(STSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretVolume) DeepCopyInto(out *SecretVolume) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretVolume.
func (in *SecretVolume) DeepCopy() *SecretVolume {
	if in == nil {
		return nil
	}
	out := new(SecretVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccount) DeepCopyInto(out *ServiceAccount) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccount.
func (in *ServiceAccount) DeepCopy() *ServiceAccount {
	if in == nil {
		return nil
	}
	out := new(ServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSettingsSettings) DeepCopyInto(out *ServiceSettingsSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSettingsSettings.
func (in *ServiceSettingsSettings) DeepCopy() *ServiceSettingsSettings {
	if in == nil {
		return nil
	}
	out := new(ServiceSettingsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarInjectorConfig) DeepCopyInto(out *SidecarInjectorConfig) {
	*out = *in
	if in.NeverInjectSelector != nil {
		in, out := &in.NeverInjectSelector, &out.NeverInjectSelector
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.AlwaysInjectSelector != nil {
		in, out := &in.AlwaysInjectSelector, &out.AlwaysInjectSelector
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
	if in.InjectedAnnotations != nil {
		in, out := &in.InjectedAnnotations, &out.InjectedAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ObjectSelector != nil {
		in, out := &in.ObjectSelector, &out.ObjectSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefaultTemplates != nil {
		in, out := &in.DefaultTemplates, &out.DefaultTemplates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarInjectorConfig.
func (in *SidecarInjectorConfig) DeepCopy() *SidecarInjectorConfig {
	if in == nil {
		return nil
	}
	out := new(SidecarInjectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupProbe) DeepCopyInto(out *StartupProbe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupProbe.
func (in *StartupProbe) DeepCopy() *StartupProbe {
	if in == nil {
		return nil
	}
	out := new(StartupProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.EcdhCurves != nil {
		in, out := &in.EcdhCurves, &out.EcdhCurves
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CipherSuites != nil {
		in, out := &in.CipherSuites, &out.CipherSuites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryConfig) DeepCopyInto(out *TelemetryConfig) {
	*out = *in
	if in.V2 != nil {
		in, out := &in.V2, &out.V2
		*out = new(TelemetryV2Config)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryConfig.
func (in *TelemetryConfig) DeepCopy() *TelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(TelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryV2Config) DeepCopyInto(out *TelemetryV2Config) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(TelemetryV2PrometheusConfig)
		**out = **in
	}
	if in.Stackdriver != nil {
		in, out := &in.Stackdriver, &out.Stackdriver
		*out = new(TelemetryV2StackDriverConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryV2Config.
func (in *TelemetryV2Config) DeepCopy() *TelemetryV2Config {
	if in == nil {
		return nil
	}
	out := new(TelemetryV2Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryV2PrometheusConfig) DeepCopyInto(out *TelemetryV2PrometheusConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryV2PrometheusConfig.
func (in *TelemetryV2PrometheusConfig) DeepCopy() *TelemetryV2PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(TelemetryV2PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryV2StackDriverConfig) DeepCopyInto(out *TelemetryV2StackDriverConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryV2StackDriverConfig.
func (in *TelemetryV2StackDriverConfig) DeepCopy() *TelemetryV2StackDriverConfig {
	if in == nil {
		return nil
	}
	out := new(TelemetryV2StackDriverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracerConfig) DeepCopyInto(out *TracerConfig) {
	*out = *in
	if in.Datadog != nil {
		in, out := &in.Datadog, &out.Datadog
		*out = new(TracerDatadogConfig)
		**out = **in
	}
	if in.Lightstep != nil {
		in, out := &in.Lightstep, &out.Lightstep
		*out = new(TracerLightStepConfig)
		**out = **in
	}
	if in.Zipkin != nil {
		in, out := &in.Zipkin, &out.Zipkin
		*out = new(TracerZipkinConfig)
		**out = **in
	}
	if in.Stackdriver != nil {
		in, out := &in.Stackdriver, &out.Stackdriver
		*out = new(TracerStackdriverConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracerConfig.
func (in *TracerConfig) DeepCopy() *TracerConfig {
	if in == nil {
		return nil
	}
	out := new(TracerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracerDatadogConfig) DeepCopyInto(out *TracerDatadogConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracerDatadogConfig.
func (in *TracerDatadogConfig) DeepCopy() *TracerDatadogConfig {
	if in == nil {
		return nil
	}
	out := new(TracerDatadogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracerLightStepConfig) DeepCopyInto(out *TracerLightStepConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracerLightStepConfig.
func (in *TracerLightStepConfig) DeepCopy() *TracerLightStepConfig {
	if in == nil {
		return nil
	}
	out := new(TracerLightStepConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracerStackdriverConfig) DeepCopyInto(out *TracerStackdriverConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracerStackdriverConfig.
func (in *TracerStackdriverConfig) DeepCopy() *TracerStackdriverConfig {
	if in == nil {
		return nil
	}
	out := new(TracerStackdriverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracerZipkinConfig) DeepCopyInto(out *TracerZipkinConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracerZipkinConfig.
func (in *TracerZipkinConfig) DeepCopy() *TracerZipkinConfig {
	if in == nil {
		return nil
	}
	out := new(TracerZipkinConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Values) DeepCopyInto(out *Values) {
	*out = *in
	if in.Cni != nil {
		in, out := &in.Cni, &out.Cni
		*out = new(CNIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = new(GatewaysConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = new(GlobalConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Pilot != nil {
		in, out := &in.Pilot, &out.Pilot
		*out = new(PilotConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ztunnel != nil {
		in, out := &in.Ztunnel, &out.Ztunnel
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SidecarInjectorWebhook != nil {
		in, out := &in.SidecarInjectorWebhook, &out.SidecarInjectorWebhook
		*out = new(SidecarInjectorConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.IstioCni != nil {
		in, out := &in.IstioCni, &out.IstioCni
		*out = new(CNIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MeshConfig != nil {
		in, out := &in.MeshConfig, &out.MeshConfig
		*out = new(MeshConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Base != nil {
		in, out := &in.Base, &out.Base
		*out = new(BaseConfig)
		**out = **in
	}
	if in.IstiodRemote != nil {
		in, out := &in.IstiodRemote, &out.IstiodRemote
		*out = new(IstiodRemoteConfig)
		**out = **in
	}
	if in.RevisionTags != nil {
		in, out := &in.RevisionTags, &out.RevisionTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Values.
func (in *Values) DeepCopy() *Values {
	if in == nil {
		return nil
	}
	out := new(Values)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZeroVPNConfig) DeepCopyInto(out *ZeroVPNConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZeroVPNConfig.
func (in *ZeroVPNConfig) DeepCopy() *ZeroVPNConfig {
	if in == nil {
		return nil
	}
	out := new(ZeroVPNConfig)
	in.DeepCopyInto(out)
	return out
}
