apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ossm-mec
  labels:
    maistra-version: 2.0.0
    release: {{ .Release.Name }}
    app: mec
rules:
- apiGroups:
  - extensions.maistra.io
  resources:
  - servicemeshextensions
  - servicemeshextensions/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - maistra.io
  resources:
  - servicemeshmemberrolls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreamimports
  verbs:
  - create
  - update
  - get
  - list
  - watch
