apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-sidecar-injector
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: 1.2.0
    app: {{ template "sidecar-injector.name" . }}
    chart: {{ template "sidecar-injector.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: sidecar-injector
  annotations:
    "maistra.io/internal": "true"
spec:
  podSelector:
    matchLabels:
      istio: sidecar-injector
  ingress:
  - ports:
    port: webhook
