{{ if and .Values.tracing.enabled (eq .Values.tracing.provider "jaeger") }}

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: disable-mtls-jaeger-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.provider }}
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: jaeger-collector
  mtls:
    mode: DISABLED
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-jaeger-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.provider }}
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  host: jaeger-collector
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: disable-mtls-zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.provider }}
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: zipkin
  mtls:
    mode: DISABLED
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls-zipkin
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.provider }}
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  host: zipkin
  trafficPolicy:
    tls:
      mode: DISABLE

{{ end }}
