apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istiod-pilot-{{ .Values.global.istioNamespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: 2.0.0
    app: pilot
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiod-{{ .Values.global.istioNamespace }}
subjects:
  - kind: ServiceAccount
    name: istiod-service-account-{{ .Values.revision | default "default" }}
    namespace: {{ .Values.global.istioNamespace }}
---
