apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio
    chart: {{ template "istio.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          "maistra.io/member-of": "{{ .Release.Namespace }}"
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          "maistra.io/member-of": "{{ .Release.Namespace }}"

---

# this will work for all routes into the mesh namespace, but not on ocp 3.11
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-ingress-router
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio
    chart: {{ template "istio.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress

---

# this will work for all routes into the mesh namespace referencing a labelled pod, but not on ocp 3.11
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-expose-route
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "istio.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      maistra.io/expose-route: "true"
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
