apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    istio: pilot
    istio.io/rev: {{ .Values.revision | default "default" }}
    release: {{ .Release.Name }}
  annotations:
    "maistra.io/internal": "true"
spec:
  podSelector:
    matchLabels:
      istio: istiod
      istio.io/rev: {{ .Values.revision | default "default" }}
  ingress:
  - ports:
    port: webhook
