apiVersion: v1
data:
  auth: ""
  rawPassword: ""
kind: Secret
metadata:
  name: htpasswd
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio
    chart: {{ template "istio.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
