{{- if not (and (.Values.dashboard.user) (.Values.dashboard.passphrase)) }}
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: kiali
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
redirectURIs:
  - localhost:3000
grantMethod: auto
allowAnyScope: true
{{- end }}
