apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-policy-admin-role-binding-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: 1.2.0
    app: istio-policy
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-policy
subjects:
  - kind: ServiceAccount
    name: istio-policy-service-account
    namespace: {{ .Release.Namespace }}
---
