// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v2

import (
	appsv1 "k8s.io/api/apps/v1"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessLogTelemetryFilterConfig) DeepCopyInto(out *AccessLogTelemetryFilterConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessLogTelemetryFilterConfig.
func (in *AccessLogTelemetryFilterConfig) DeepCopy() *AccessLogTelemetryFilterConfig {
	if in == nil {
		return nil
	}
	out := new(AccessLogTelemetryFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonsConfig) DeepCopyInto(out *AddonsConfig) {
	*out = *in
	in.Metrics.DeepCopyInto(&out.Metrics)
	in.Tracing.DeepCopyInto(&out.Tracing)
	in.Visualization.DeepCopyInto(&out.Visualization)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonsConfig.
func (in *AddonsConfig) DeepCopy() *AddonsConfig {
	if in == nil {
		return nil
	}
	out := new(AddonsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Affinity) DeepCopyInto(out *Affinity) {
	*out = *in
	if in.PodAntiAffinity != nil {
		in, out := &in.PodAntiAffinity, &out.PodAntiAffinity
		*out = new(PodAntiAffinity)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Affinity.
func (in *Affinity) DeepCopy() *Affinity {
	if in == nil {
		return nil
	}
	out := new(Affinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoScalerConfig) DeepCopyInto(out *AutoScalerConfig) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoScalerConfig.
func (in *AutoScalerConfig) DeepCopy() *AutoScalerConfig {
	if in == nil {
		return nil
	}
	out := new(AutoScalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAuthorityConfig) DeepCopyInto(out *CertificateAuthorityConfig) {
	*out = *in
	if in.Istiod != nil {
		in, out := &in.Istiod, &out.Istiod
		*out = new(IstiodCertificateAuthorityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(CustomCertificateAuthorityConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAuthorityConfig.
func (in *CertificateAuthorityConfig) DeepCopy() *CertificateAuthorityConfig {
	if in == nil {
		return nil
	}
	out := new(CertificateAuthorityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonContainerConfig) DeepCopyInto(out *CommonContainerConfig) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonContainerConfig.
func (in *CommonContainerConfig) DeepCopy() *CommonContainerConfig {
	if in == nil {
		return nil
	}
	out := new(CommonContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonDeploymentRuntimeConfig) DeepCopyInto(out *CommonDeploymentRuntimeConfig) {
	*out = *in
	if in.Disruption != nil {
		in, out := &in.Disruption, &out.Disruption
		*out = new(PodDisruptionBudget)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonDeploymentRuntimeConfig.
func (in *CommonDeploymentRuntimeConfig) DeepCopy() *CommonDeploymentRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(CommonDeploymentRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonPodRuntimeConfig) DeepCopyInto(out *CommonPodRuntimeConfig) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonPodRuntimeConfig.
func (in *CommonPodRuntimeConfig) DeepCopy() *CommonPodRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(CommonPodRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentIngressConfig) DeepCopyInto(out *ComponentIngressConfig) {
	*out = *in
	out.Enablement = in.Enablement
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentIngressConfig.
func (in *ComponentIngressConfig) DeepCopy() *ComponentIngressConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentIngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ComponentLogLevels) DeepCopyInto(out *ComponentLogLevels) {
	{
		in := &in
		*out = make(ComponentLogLevels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentLogLevels.
func (in ComponentLogLevels) DeepCopy() ComponentLogLevels {
	if in == nil {
		return nil
	}
	out := new(ComponentLogLevels)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentPersistenceConfig) DeepCopyInto(out *ComponentPersistenceConfig) {
	*out = *in
	out.Enablement = in.Enablement
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentPersistenceConfig.
func (in *ComponentPersistenceConfig) DeepCopy() *ComponentPersistenceConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentPersistenceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentRuntimeConfig) DeepCopyInto(out *ComponentRuntimeConfig) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	in.Pod.DeepCopyInto(&out.Pod)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentRuntimeConfig.
func (in *ComponentRuntimeConfig) DeepCopy() *ComponentRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentServiceConfig) DeepCopyInto(out *ComponentServiceConfig) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(ComponentIngressConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentServiceConfig.
func (in *ComponentServiceConfig) DeepCopy() *ComponentServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerConfig) DeepCopyInto(out *ContainerConfig) {
	*out = *in
	in.CommonContainerConfig.DeepCopyInto(&out.CommonContainerConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerConfig.
func (in *ContainerConfig) DeepCopy() *ContainerConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneClusterConfig) DeepCopyInto(out *ControlPlaneClusterConfig) {
	*out = *in
	if in.MultiCluster != nil {
		in, out := &in.MultiCluster, &out.MultiCluster
		*out = new(MultiClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MeshExpansion != nil {
		in, out := &in.MeshExpansion, &out.MeshExpansion
		*out = new(MeshExpansionConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneClusterConfig.
func (in *ControlPlaneClusterConfig) DeepCopy() *ControlPlaneClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneMTLSConfig) DeepCopyInto(out *ControlPlaneMTLSConfig) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneMTLSConfig.
func (in *ControlPlaneMTLSConfig) DeepCopy() *ControlPlaneMTLSConfig {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneMTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneRuntimeConfig) DeepCopyInto(out *ControlPlaneRuntimeConfig) {
	*out = *in
	if in.Citadel != nil {
		in, out := &in.Citadel, &out.Citadel
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Galley != nil {
		in, out := &in.Galley, &out.Galley
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Pilot != nil {
		in, out := &in.Pilot, &out.Pilot
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(DefaultRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneRuntimeConfig.
func (in *ControlPlaneRuntimeConfig) DeepCopy() *ControlPlaneRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneSpec) DeepCopyInto(out *ControlPlaneSpec) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(ControlPlaneClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(PolicyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecurityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = new(GatewaysConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ControlPlaneRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Addons != nil {
		in, out := &in.Addons, &out.Addons
		*out = new(AddonsConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneSpec.
func (in *ControlPlaneSpec) DeepCopy() *ControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneStatus) DeepCopyInto(out *ControlPlaneStatus) {
	*out = *in
	in.ControlPlaneStatus.DeepCopyInto(&out.ControlPlaneStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneStatus.
func (in *ControlPlaneStatus) DeepCopy() *ControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomCertificateAuthorityConfig) DeepCopyInto(out *CustomCertificateAuthorityConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomCertificateAuthorityConfig.
func (in *CustomCertificateAuthorityConfig) DeepCopy() *CustomCertificateAuthorityConfig {
	if in == nil {
		return nil
	}
	out := new(CustomCertificateAuthorityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogTracerConfig) DeepCopyInto(out *DatadogTracerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogTracerConfig.
func (in *DatadogTracerConfig) DeepCopy() *DatadogTracerConfig {
	if in == nil {
		return nil
	}
	out := new(DatadogTracerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultRuntimeConfig) DeepCopyInto(out *DefaultRuntimeConfig) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(CommonDeploymentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(CommonPodRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(CommonContainerConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultRuntimeConfig.
func (in *DefaultRuntimeConfig) DeepCopy() *DefaultRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(DefaultRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentRuntimeConfig) DeepCopyInto(out *DeploymentRuntimeConfig) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(appsv1.DeploymentStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoScaling != nil {
		in, out := &in.AutoScaling, &out.AutoScaling
		*out = new(AutoScalerConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentRuntimeConfig.
func (in *DeploymentRuntimeConfig) DeepCopy() *DeploymentRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(DeploymentRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Enablement) DeepCopyInto(out *Enablement) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Enablement.
func (in *Enablement) DeepCopy() *Enablement {
	if in == nil {
		return nil
	}
	out := new(Enablement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfig) DeepCopyInto(out *GatewayConfig) {
	*out = *in
	out.Enablement = in.Enablement
	in.Service.DeepCopyInto(&out.Service)
	if in.RequestedNetworkView != nil {
		in, out := &in.RequestedNetworkView, &out.RequestedNetworkView
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EnableSDS != nil {
		in, out := &in.EnableSDS, &out.EnableSDS
		*out = new(bool)
		**out = **in
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]VolumeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfig.
func (in *GatewayConfig) DeepCopy() *GatewayConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayServiceConfig) DeepCopyInto(out *GatewayServiceConfig) {
	*out = *in
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
	in.Metadata.DeepCopyInto(&out.Metadata)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayServiceConfig.
func (in *GatewayServiceConfig) DeepCopy() *GatewayServiceConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayVolume) DeepCopyInto(out *GatewayVolume) {
	*out = *in
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(v1.ConfigMapVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.SecretVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayVolume.
func (in *GatewayVolume) DeepCopy() *GatewayVolume {
	if in == nil {
		return nil
	}
	out := new(GatewayVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaysConfig) DeepCopyInto(out *GatewaysConfig) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressGatewayConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = new(GatewayConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalGateways != nil {
		in, out := &in.AdditionalGateways, &out.AdditionalGateways
		*out = make(map[string]GatewayConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaysConfig.
func (in *GatewaysConfig) DeepCopy() *GatewaysConfig {
	if in == nil {
		return nil
	}
	out := new(GatewaysConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaAddonConfig) DeepCopyInto(out *GrafanaAddonConfig) {
	*out = *in
	out.Enablement = in.Enablement
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = new(GrafanaInstallConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaAddonConfig.
func (in *GrafanaAddonConfig) DeepCopy() *GrafanaAddonConfig {
	if in == nil {
		return nil
	}
	out := new(GrafanaAddonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaConfig) DeepCopyInto(out *GrafanaConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnvSecrets != nil {
		in, out := &in.EnvSecrets, &out.EnvSecrets
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaConfig.
func (in *GrafanaConfig) DeepCopy() *GrafanaConfig {
	if in == nil {
		return nil
	}
	out := new(GrafanaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaInstallConfig) DeepCopyInto(out *GrafanaInstallConfig) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.Service.DeepCopyInto(&out.Service)
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(ComponentPersistenceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(GrafanaSecurityConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaInstallConfig.
func (in *GrafanaInstallConfig) DeepCopy() *GrafanaInstallConfig {
	if in == nil {
		return nil
	}
	out := new(GrafanaInstallConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GrafanaSecurityConfig) DeepCopyInto(out *GrafanaSecurityConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GrafanaSecurityConfig.
func (in *GrafanaSecurityConfig) DeepCopy() *GrafanaSecurityConfig {
	if in == nil {
		return nil
	}
	out := new(GrafanaSecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityConfig) DeepCopyInto(out *IdentityConfig) {
	*out = *in
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesIdentityConfig)
		**out = **in
	}
	if in.ThirdParty != nil {
		in, out := &in.ThirdParty, &out.ThirdParty
		*out = new(ThirdPartyIdentityConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityConfig.
func (in *IdentityConfig) DeepCopy() *IdentityConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressGatewayConfig) DeepCopyInto(out *IngressGatewayConfig) {
	*out = *in
	in.GatewayConfig.DeepCopyInto(&out.GatewayConfig)
	if in.MeshExpansionPorts != nil {
		in, out := &in.MeshExpansionPorts, &out.MeshExpansionPorts
		*out = make([]v1.ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressGatewayConfig.
func (in *IngressGatewayConfig) DeepCopy() *IngressGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(IngressGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioPrivateKeyCertificateSignerConfig) DeepCopyInto(out *IstioPrivateKeyCertificateSignerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioPrivateKeyCertificateSignerConfig.
func (in *IstioPrivateKeyCertificateSignerConfig) DeepCopy() *IstioPrivateKeyCertificateSignerConfig {
	if in == nil {
		return nil
	}
	out := new(IstioPrivateKeyCertificateSignerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioSelfSignedCertificateSignerConfig) DeepCopyInto(out *IstioSelfSignedCertificateSignerConfig) {
	*out = *in
	if in.EnableJitter != nil {
		in, out := &in.EnableJitter, &out.EnableJitter
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioSelfSignedCertificateSignerConfig.
func (in *IstioSelfSignedCertificateSignerConfig) DeepCopy() *IstioSelfSignedCertificateSignerConfig {
	if in == nil {
		return nil
	}
	out := new(IstioSelfSignedCertificateSignerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstiodCertificateAuthorityConfig) DeepCopyInto(out *IstiodCertificateAuthorityConfig) {
	*out = *in
	if in.SelfSigned != nil {
		in, out := &in.SelfSigned, &out.SelfSigned
		*out = new(IstioSelfSignedCertificateSignerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(IstioPrivateKeyCertificateSignerConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstiodCertificateAuthorityConfig.
func (in *IstiodCertificateAuthorityConfig) DeepCopy() *IstiodCertificateAuthorityConfig {
	if in == nil {
		return nil
	}
	out := new(IstiodCertificateAuthorityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstiodPolicyConfig) DeepCopyInto(out *IstiodPolicyConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstiodPolicyConfig.
func (in *IstiodPolicyConfig) DeepCopy() *IstiodPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(IstiodPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstiodTelemetryConfig) DeepCopyInto(out *IstiodTelemetryConfig) {
	*out = *in
	if in.MetadataExchange != nil {
		in, out := &in.MetadataExchange, &out.MetadataExchange
		*out = new(MetadataExchangeConfig)
		**out = **in
	}
	if in.PrometheusFilter != nil {
		in, out := &in.PrometheusFilter, &out.PrometheusFilter
		*out = new(PrometheusFilterConfig)
		**out = **in
	}
	if in.StackDriverFilter != nil {
		in, out := &in.StackDriverFilter, &out.StackDriverFilter
		*out = new(StackDriverFilterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AccessLogTelemetryFilter != nil {
		in, out := &in.AccessLogTelemetryFilter, &out.AccessLogTelemetryFilter
		*out = new(AccessLogTelemetryFilterConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstiodTelemetryConfig.
func (in *IstiodTelemetryConfig) DeepCopy() *IstiodTelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(IstiodTelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaegerConfig) DeepCopyInto(out *JaegerConfig) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(JaegerStorageConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaegerConfig.
func (in *JaegerConfig) DeepCopy() *JaegerConfig {
	if in == nil {
		return nil
	}
	out := new(JaegerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaegerElasticsearchStorageConfig) DeepCopyInto(out *JaegerElasticsearchStorageConfig) {
	*out = *in
	if in.NodeCount != nil {
		in, out := &in.NodeCount, &out.NodeCount
		*out = new(int32)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RedundancyPolicy != nil {
		in, out := &in.RedundancyPolicy, &out.RedundancyPolicy
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IndexCleaner != nil {
		in, out := &in.IndexCleaner, &out.IndexCleaner
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(PodRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaegerElasticsearchStorageConfig.
func (in *JaegerElasticsearchStorageConfig) DeepCopy() *JaegerElasticsearchStorageConfig {
	if in == nil {
		return nil
	}
	out := new(JaegerElasticsearchStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaegerIngressConfig) DeepCopyInto(out *JaegerIngressConfig) {
	*out = *in
	out.Enablement = in.Enablement
	in.Metadata.DeepCopyInto(&out.Metadata)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaegerIngressConfig.
func (in *JaegerIngressConfig) DeepCopy() *JaegerIngressConfig {
	if in == nil {
		return nil
	}
	out := new(JaegerIngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaegerInstallConfig) DeepCopyInto(out *JaegerInstallConfig) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(JaegerIngressConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaegerInstallConfig.
func (in *JaegerInstallConfig) DeepCopy() *JaegerInstallConfig {
	if in == nil {
		return nil
	}
	out := new(JaegerInstallConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaegerMemoryStorageConfig) DeepCopyInto(out *JaegerMemoryStorageConfig) {
	*out = *in
	if in.MaxTraces != nil {
		in, out := &in.MaxTraces, &out.MaxTraces
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaegerMemoryStorageConfig.
func (in *JaegerMemoryStorageConfig) DeepCopy() *JaegerMemoryStorageConfig {
	if in == nil {
		return nil
	}
	out := new(JaegerMemoryStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaegerStorageConfig) DeepCopyInto(out *JaegerStorageConfig) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(JaegerMemoryStorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Elasticsearch != nil {
		in, out := &in.Elasticsearch, &out.Elasticsearch
		*out = new(JaegerElasticsearchStorageConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaegerStorageConfig.
func (in *JaegerStorageConfig) DeepCopy() *JaegerStorageConfig {
	if in == nil {
		return nil
	}
	out := new(JaegerStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaegerTracerConfig) DeepCopyInto(out *JaegerTracerConfig) {
	*out = *in
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = new(JaegerInstallConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaegerTracerConfig.
func (in *JaegerTracerConfig) DeepCopy() *JaegerTracerConfig {
	if in == nil {
		return nil
	}
	out := new(JaegerTracerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KialiAddonConfig) DeepCopyInto(out *KialiAddonConfig) {
	*out = *in
	out.Enablement = in.Enablement
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = new(KialiInstallConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KialiAddonConfig.
func (in *KialiAddonConfig) DeepCopy() *KialiAddonConfig {
	if in == nil {
		return nil
	}
	out := new(KialiAddonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KialiConfig) DeepCopyInto(out *KialiConfig) {
	*out = *in
	in.Dashboard.DeepCopyInto(&out.Dashboard)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KialiConfig.
func (in *KialiConfig) DeepCopy() *KialiConfig {
	if in == nil {
		return nil
	}
	out := new(KialiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KialiDashboardConfig) DeepCopyInto(out *KialiDashboardConfig) {
	*out = *in
	if in.ViewOnly != nil {
		in, out := &in.ViewOnly, &out.ViewOnly
		*out = new(bool)
		**out = **in
	}
	if in.EnableGrafana != nil {
		in, out := &in.EnableGrafana, &out.EnableGrafana
		*out = new(bool)
		**out = **in
	}
	if in.EnablePrometheus != nil {
		in, out := &in.EnablePrometheus, &out.EnablePrometheus
		*out = new(bool)
		**out = **in
	}
	if in.EnableTracing != nil {
		in, out := &in.EnableTracing, &out.EnableTracing
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KialiDashboardConfig.
func (in *KialiDashboardConfig) DeepCopy() *KialiDashboardConfig {
	if in == nil {
		return nil
	}
	out := new(KialiDashboardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KialiInstallConfig) DeepCopyInto(out *KialiInstallConfig) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.Service.DeepCopyInto(&out.Service)
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KialiInstallConfig.
func (in *KialiInstallConfig) DeepCopy() *KialiInstallConfig {
	if in == nil {
		return nil
	}
	out := new(KialiInstallConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesIdentityConfig) DeepCopyInto(out *KubernetesIdentityConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesIdentityConfig.
func (in *KubernetesIdentityConfig) DeepCopy() *KubernetesIdentityConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesIdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightstepTracerConfig) DeepCopyInto(out *LightstepTracerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightstepTracerConfig.
func (in *LightstepTracerConfig) DeepCopy() *LightstepTracerConfig {
	if in == nil {
		return nil
	}
	out := new(LightstepTracerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
	if in.ComponentLevels != nil {
		in, out := &in.ComponentLevels, &out.ComponentLevels
		*out = make(ComponentLogLevels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LogAsJSON != nil {
		in, out := &in.LogAsJSON, &out.LogAsJSON
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshEndpointConfig) DeepCopyInto(out *MeshEndpointConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshEndpointConfig.
func (in *MeshEndpointConfig) DeepCopy() *MeshEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(MeshEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshExpansionConfig) DeepCopyInto(out *MeshExpansionConfig) {
	*out = *in
	if in.ILBGateway != nil {
		in, out := &in.ILBGateway, &out.ILBGateway
		*out = new(GatewayConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshExpansionConfig.
func (in *MeshExpansionConfig) DeepCopy() *MeshExpansionConfig {
	if in == nil {
		return nil
	}
	out := new(MeshExpansionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshGatewayConfig) DeepCopyInto(out *MeshGatewayConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayConfig.
func (in *MeshGatewayConfig) DeepCopy() *MeshGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(MeshGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshNetworkConfig) DeepCopyInto(out *MeshNetworkConfig) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]MeshEndpointConfig, len(*in))
		copy(*out, *in)
	}
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = make([]MeshGatewayConfig, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshNetworkConfig.
func (in *MeshNetworkConfig) DeepCopy() *MeshNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(MeshNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataConfig) DeepCopyInto(out *MetadataConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataConfig.
func (in *MetadataConfig) DeepCopy() *MetadataConfig {
	if in == nil {
		return nil
	}
	out := new(MetadataConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataExchangeConfig) DeepCopyInto(out *MetadataExchangeConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataExchangeConfig.
func (in *MetadataExchangeConfig) DeepCopy() *MetadataExchangeConfig {
	if in == nil {
		return nil
	}
	out := new(MetadataExchangeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsAddonsConfig) DeepCopyInto(out *MetricsAddonsConfig) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusAddonConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsAddonsConfig.
func (in *MetricsAddonsConfig) DeepCopy() *MetricsAddonsConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsAddonsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerPolicyAdaptersConfig) DeepCopyInto(out *MixerPolicyAdaptersConfig) {
	*out = *in
	if in.UseAdapterCRDs != nil {
		in, out := &in.UseAdapterCRDs, &out.UseAdapterCRDs
		*out = new(bool)
		**out = **in
	}
	if in.KubernetesEnv != nil {
		in, out := &in.KubernetesEnv, &out.KubernetesEnv
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerPolicyAdaptersConfig.
func (in *MixerPolicyAdaptersConfig) DeepCopy() *MixerPolicyAdaptersConfig {
	if in == nil {
		return nil
	}
	out := new(MixerPolicyAdaptersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerPolicyConfig) DeepCopyInto(out *MixerPolicyConfig) {
	*out = *in
	if in.EnableChecks != nil {
		in, out := &in.EnableChecks, &out.EnableChecks
		*out = new(bool)
		**out = **in
	}
	if in.FailOpen != nil {
		in, out := &in.FailOpen, &out.FailOpen
		*out = new(bool)
		**out = **in
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Adapters != nil {
		in, out := &in.Adapters, &out.Adapters
		*out = new(MixerPolicyAdaptersConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerPolicyConfig.
func (in *MixerPolicyConfig) DeepCopy() *MixerPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(MixerPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerTelemetryAdaptersConfig) DeepCopyInto(out *MixerTelemetryAdaptersConfig) {
	*out = *in
	if in.UseAdapterCRDs != nil {
		in, out := &in.UseAdapterCRDs, &out.UseAdapterCRDs
		*out = new(bool)
		**out = **in
	}
	if in.KubernetesEnv != nil {
		in, out := &in.KubernetesEnv, &out.KubernetesEnv
		*out = new(bool)
		**out = **in
	}
	if in.Stdio != nil {
		in, out := &in.Stdio, &out.Stdio
		*out = new(MixerTelemetryStdioConfig)
		**out = **in
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(MixerTelemetryPrometheusConfig)
		**out = **in
	}
	if in.Stackdriver != nil {
		in, out := &in.Stackdriver, &out.Stackdriver
		*out = new(MixerTelemetryStackdriverConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerTelemetryAdaptersConfig.
func (in *MixerTelemetryAdaptersConfig) DeepCopy() *MixerTelemetryAdaptersConfig {
	if in == nil {
		return nil
	}
	out := new(MixerTelemetryAdaptersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerTelemetryConfig) DeepCopyInto(out *MixerTelemetryConfig) {
	*out = *in
	if in.SessionAffinity != nil {
		in, out := &in.SessionAffinity, &out.SessionAffinity
		*out = new(bool)
		**out = **in
	}
	in.Batching.DeepCopyInto(&out.Batching)
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Adapters != nil {
		in, out := &in.Adapters, &out.Adapters
		*out = new(MixerTelemetryAdaptersConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerTelemetryConfig.
func (in *MixerTelemetryConfig) DeepCopy() *MixerTelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(MixerTelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerTelemetryPrometheusConfig) DeepCopyInto(out *MixerTelemetryPrometheusConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerTelemetryPrometheusConfig.
func (in *MixerTelemetryPrometheusConfig) DeepCopy() *MixerTelemetryPrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(MixerTelemetryPrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerTelemetryStackdriverAuthConfig) DeepCopyInto(out *MixerTelemetryStackdriverAuthConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerTelemetryStackdriverAuthConfig.
func (in *MixerTelemetryStackdriverAuthConfig) DeepCopy() *MixerTelemetryStackdriverAuthConfig {
	if in == nil {
		return nil
	}
	out := new(MixerTelemetryStackdriverAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerTelemetryStackdriverConfig) DeepCopyInto(out *MixerTelemetryStackdriverConfig) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(MixerTelemetryStackdriverAuthConfig)
		**out = **in
	}
	if in.Tracer != nil {
		in, out := &in.Tracer, &out.Tracer
		*out = new(MixerTelemetryStackdriverTracerConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerTelemetryStackdriverConfig.
func (in *MixerTelemetryStackdriverConfig) DeepCopy() *MixerTelemetryStackdriverConfig {
	if in == nil {
		return nil
	}
	out := new(MixerTelemetryStackdriverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerTelemetryStackdriverTracerConfig) DeepCopyInto(out *MixerTelemetryStackdriverTracerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerTelemetryStackdriverTracerConfig.
func (in *MixerTelemetryStackdriverTracerConfig) DeepCopy() *MixerTelemetryStackdriverTracerConfig {
	if in == nil {
		return nil
	}
	out := new(MixerTelemetryStackdriverTracerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerTelemetryStdioConfig) DeepCopyInto(out *MixerTelemetryStdioConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerTelemetryStdioConfig.
func (in *MixerTelemetryStdioConfig) DeepCopy() *MixerTelemetryStdioConfig {
	if in == nil {
		return nil
	}
	out := new(MixerTelemetryStdioConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterConfig) DeepCopyInto(out *MultiClusterConfig) {
	*out = *in
	if in.MeshNetworks != nil {
		in, out := &in.MeshNetworks, &out.MeshNetworks
		*out = make(map[string]MeshNetworkConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterConfig.
func (in *MultiClusterConfig) DeepCopy() *MultiClusterConfig {
	if in == nil {
		return nil
	}
	out := new(MultiClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutualTLSConfig) DeepCopyInto(out *MutualTLSConfig) {
	*out = *in
	if in.Auto != nil {
		in, out := &in.Auto, &out.Auto
		*out = new(bool)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	in.Trust.DeepCopyInto(&out.Trust)
	in.CertificateAuthority.DeepCopyInto(&out.CertificateAuthority)
	in.Identity.DeepCopyInto(&out.Identity)
	in.ControlPlane.DeepCopyInto(&out.ControlPlane)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutualTLSConfig.
func (in *MutualTLSConfig) DeepCopy() *MutualTLSConfig {
	if in == nil {
		return nil
	}
	out := new(MutualTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAntiAffinity) DeepCopyInto(out *PodAntiAffinity) {
	*out = *in
	if in.RequiredDuringScheduling != nil {
		in, out := &in.RequiredDuringScheduling, &out.RequiredDuringScheduling
		*out = make([]PodAntiAffinityTerm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreferredDuringScheduling != nil {
		in, out := &in.PreferredDuringScheduling, &out.PreferredDuringScheduling
		*out = make([]PodAntiAffinityTerm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAntiAffinity.
func (in *PodAntiAffinity) DeepCopy() *PodAntiAffinity {
	if in == nil {
		return nil
	}
	out := new(PodAntiAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAntiAffinityTerm) DeepCopyInto(out *PodAntiAffinityTerm) {
	*out = *in
	in.LabelSelectorRequirement.DeepCopyInto(&out.LabelSelectorRequirement)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAntiAffinityTerm.
func (in *PodAntiAffinityTerm) DeepCopy() *PodAntiAffinityTerm {
	if in == nil {
		return nil
	}
	out := new(PodAntiAffinityTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisruptionBudget) DeepCopyInto(out *PodDisruptionBudget) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisruptionBudget.
func (in *PodDisruptionBudget) DeepCopy() *PodDisruptionBudget {
	if in == nil {
		return nil
	}
	out := new(PodDisruptionBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRuntimeConfig) DeepCopyInto(out *PodRuntimeConfig) {
	*out = *in
	in.CommonPodRuntimeConfig.DeepCopyInto(&out.CommonPodRuntimeConfig)
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make(map[string]ContainerConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRuntimeConfig.
func (in *PodRuntimeConfig) DeepCopy() *PodRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(PodRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyConfig) DeepCopyInto(out *PolicyConfig) {
	*out = *in
	if in.Mixer != nil {
		in, out := &in.Mixer, &out.Mixer
		*out = new(MixerPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(RemotePolicyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Istiod != nil {
		in, out := &in.Istiod, &out.Istiod
		*out = new(IstiodPolicyConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyConfig.
func (in *PolicyConfig) DeepCopy() *PolicyConfig {
	if in == nil {
		return nil
	}
	out := new(PolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusAddonConfig) DeepCopyInto(out *PrometheusAddonConfig) {
	*out = *in
	out.Enablement = in.Enablement
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = new(PrometheusInstallConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusAddonConfig.
func (in *PrometheusAddonConfig) DeepCopy() *PrometheusAddonConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusAddonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusFilterConfig) DeepCopyInto(out *PrometheusFilterConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusFilterConfig.
func (in *PrometheusFilterConfig) DeepCopy() *PrometheusFilterConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusInstallConfig) DeepCopyInto(out *PrometheusInstallConfig) {
	*out = *in
	out.Config = in.Config
	in.Service.DeepCopyInto(&out.Service)
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ComponentRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UseTLS != nil {
		in, out := &in.UseTLS, &out.UseTLS
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusInstallConfig.
func (in *PrometheusInstallConfig) DeepCopy() *PrometheusInstallConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusInstallConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyCNIConfig) DeepCopyInto(out *ProxyCNIConfig) {
	*out = *in
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ProxyCNIRuntimeConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyCNIConfig.
func (in *ProxyCNIConfig) DeepCopy() *ProxyCNIConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyCNIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyCNIRuntimeConfig) DeepCopyInto(out *ProxyCNIRuntimeConfig) {
	*out = *in
	in.ContainerConfig.DeepCopyInto(&out.ContainerConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyCNIRuntimeConfig.
func (in *ProxyCNIRuntimeConfig) DeepCopy() *ProxyCNIRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyCNIRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
	in.Logging.DeepCopyInto(&out.Logging)
	in.Networking.DeepCopyInto(&out.Networking)
	in.Runtime.DeepCopyInto(&out.Runtime)
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyDNSConfig) DeepCopyInto(out *ProxyDNSConfig) {
	*out = *in
	if in.SearchSuffixes != nil {
		in, out := &in.SearchSuffixes, &out.SearchSuffixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyDNSConfig.
func (in *ProxyDNSConfig) DeepCopy() *ProxyDNSConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyInboundTrafficControlConfig) DeepCopyInto(out *ProxyInboundTrafficControlConfig) {
	*out = *in
	if in.IncludedPorts != nil {
		in, out := &in.IncludedPorts, &out.IncludedPorts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedPorts != nil {
		in, out := &in.ExcludedPorts, &out.ExcludedPorts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyInboundTrafficControlConfig.
func (in *ProxyInboundTrafficControlConfig) DeepCopy() *ProxyInboundTrafficControlConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyInboundTrafficControlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyInitContainerConfig) DeepCopyInto(out *ProxyInitContainerConfig) {
	*out = *in
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(ContainerConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyInitContainerConfig.
func (in *ProxyInitContainerConfig) DeepCopy() *ProxyInitContainerConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyInitContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyLoggingConfig) DeepCopyInto(out *ProxyLoggingConfig) {
	*out = *in
	if in.ComponentLevels != nil {
		in, out := &in.ComponentLevels, &out.ComponentLevels
		*out = make(ComponentLogLevels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyLoggingConfig.
func (in *ProxyLoggingConfig) DeepCopy() *ProxyLoggingConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyLoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyNetworkInitConfig) DeepCopyInto(out *ProxyNetworkInitConfig) {
	*out = *in
	if in.CNI != nil {
		in, out := &in.CNI, &out.CNI
		*out = new(ProxyCNIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.InitContainer != nil {
		in, out := &in.InitContainer, &out.InitContainer
		*out = new(ProxyInitContainerConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyNetworkInitConfig.
func (in *ProxyNetworkInitConfig) DeepCopy() *ProxyNetworkInitConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyNetworkInitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyNetworkProtocolConfig) DeepCopyInto(out *ProxyNetworkProtocolConfig) {
	*out = *in
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(ProxyNetworkProtocolDebugConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyNetworkProtocolConfig.
func (in *ProxyNetworkProtocolConfig) DeepCopy() *ProxyNetworkProtocolConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyNetworkProtocolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyNetworkProtocolDebugConfig) DeepCopyInto(out *ProxyNetworkProtocolDebugConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyNetworkProtocolDebugConfig.
func (in *ProxyNetworkProtocolDebugConfig) DeepCopy() *ProxyNetworkProtocolDebugConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyNetworkProtocolDebugConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyNetworkingConfig) DeepCopyInto(out *ProxyNetworkingConfig) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	in.TrafficControl.DeepCopyInto(&out.TrafficControl)
	in.Protocol.DeepCopyInto(&out.Protocol)
	in.DNS.DeepCopyInto(&out.DNS)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyNetworkingConfig.
func (in *ProxyNetworkingConfig) DeepCopy() *ProxyNetworkingConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyNetworkingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyOutboundTrafficControlConfig) DeepCopyInto(out *ProxyOutboundTrafficControlConfig) {
	*out = *in
	if in.IncludedIPRanges != nil {
		in, out := &in.IncludedIPRanges, &out.IncludedIPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedIPRanges != nil {
		in, out := &in.ExcludedIPRanges, &out.ExcludedIPRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedPorts != nil {
		in, out := &in.ExcludedPorts, &out.ExcludedPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyOutboundTrafficControlConfig.
func (in *ProxyOutboundTrafficControlConfig) DeepCopy() *ProxyOutboundTrafficControlConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyOutboundTrafficControlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyReadinessConfig) DeepCopyInto(out *ProxyReadinessConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyReadinessConfig.
func (in *ProxyReadinessConfig) DeepCopy() *ProxyReadinessConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyReadinessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyRuntimeConfig) DeepCopyInto(out *ProxyRuntimeConfig) {
	*out = *in
	out.Readiness = in.Readiness
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyRuntimeConfig.
func (in *ProxyRuntimeConfig) DeepCopy() *ProxyRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTrafficControlConfig) DeepCopyInto(out *ProxyTrafficControlConfig) {
	*out = *in
	in.Inbound.DeepCopyInto(&out.Inbound)
	in.Outbound.DeepCopyInto(&out.Outbound)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTrafficControlConfig.
func (in *ProxyTrafficControlConfig) DeepCopy() *ProxyTrafficControlConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyTrafficControlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemotePolicyConfig) DeepCopyInto(out *RemotePolicyConfig) {
	*out = *in
	if in.EnableChecks != nil {
		in, out := &in.EnableChecks, &out.EnableChecks
		*out = new(bool)
		**out = **in
	}
	if in.FailOpen != nil {
		in, out := &in.FailOpen, &out.FailOpen
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemotePolicyConfig.
func (in *RemotePolicyConfig) DeepCopy() *RemotePolicyConfig {
	if in == nil {
		return nil
	}
	out := new(RemotePolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteTelemetryConfig) DeepCopyInto(out *RemoteTelemetryConfig) {
	*out = *in
	in.Batching.DeepCopyInto(&out.Batching)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteTelemetryConfig.
func (in *RemoteTelemetryConfig) DeepCopy() *RemoteTelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(RemoteTelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	in.MutualTLS.DeepCopyInto(&out.MutualTLS)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMeshControlPlane) DeepCopyInto(out *ServiceMeshControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMeshControlPlane.
func (in *ServiceMeshControlPlane) DeepCopy() *ServiceMeshControlPlane {
	if in == nil {
		return nil
	}
	out := new(ServiceMeshControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceMeshControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMeshControlPlaneList) DeepCopyInto(out *ServiceMeshControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceMeshControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMeshControlPlaneList.
func (in *ServiceMeshControlPlaneList) DeepCopy() *ServiceMeshControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(ServiceMeshControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceMeshControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackDriverFilterConfig) DeepCopyInto(out *StackDriverFilterConfig) {
	*out = *in
	if in.ConfigOverride != nil {
		in, out := &in.ConfigOverride, &out.ConfigOverride
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackDriverFilterConfig.
func (in *StackDriverFilterConfig) DeepCopy() *StackDriverFilterConfig {
	if in == nil {
		return nil
	}
	out := new(StackDriverFilterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackdriverTracerConfig) DeepCopyInto(out *StackdriverTracerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackdriverTracerConfig.
func (in *StackdriverTracerConfig) DeepCopy() *StackdriverTracerConfig {
	if in == nil {
		return nil
	}
	out := new(StackdriverTracerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryBatchingConfig) DeepCopyInto(out *TelemetryBatchingConfig) {
	*out = *in
	if in.MaxEntries != nil {
		in, out := &in.MaxEntries, &out.MaxEntries
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryBatchingConfig.
func (in *TelemetryBatchingConfig) DeepCopy() *TelemetryBatchingConfig {
	if in == nil {
		return nil
	}
	out := new(TelemetryBatchingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryConfig) DeepCopyInto(out *TelemetryConfig) {
	*out = *in
	if in.Mixer != nil {
		in, out := &in.Mixer, &out.Mixer
		*out = new(MixerTelemetryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(RemoteTelemetryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Istiod != nil {
		in, out := &in.Istiod, &out.Istiod
		*out = new(IstiodTelemetryConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryConfig.
func (in *TelemetryConfig) DeepCopy() *TelemetryConfig {
	if in == nil {
		return nil
	}
	out := new(TelemetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThirdPartyIdentityConfig) DeepCopyInto(out *ThirdPartyIdentityConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThirdPartyIdentityConfig.
func (in *ThirdPartyIdentityConfig) DeepCopy() *ThirdPartyIdentityConfig {
	if in == nil {
		return nil
	}
	out := new(ThirdPartyIdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfig) DeepCopyInto(out *TracingConfig) {
	*out = *in
	if in.Jaeger != nil {
		in, out := &in.Jaeger, &out.Jaeger
		*out = new(JaegerTracerConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfig.
func (in *TracingConfig) DeepCopy() *TracingConfig {
	if in == nil {
		return nil
	}
	out := new(TracingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustConfig) DeepCopyInto(out *TrustConfig) {
	*out = *in
	if in.AdditionalDomains != nil {
		in, out := &in.AdditionalDomains, &out.AdditionalDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustConfig.
func (in *TrustConfig) DeepCopy() *TrustConfig {
	if in == nil {
		return nil
	}
	out := new(TrustConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VisualizationAddonsConfig) DeepCopyInto(out *VisualizationAddonsConfig) {
	*out = *in
	if in.Grafana != nil {
		in, out := &in.Grafana, &out.Grafana
		*out = new(GrafanaAddonConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Kiali != nil {
		in, out := &in.Kiali, &out.Kiali
		*out = new(KialiAddonConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VisualizationAddonsConfig.
func (in *VisualizationAddonsConfig) DeepCopy() *VisualizationAddonsConfig {
	if in == nil {
		return nil
	}
	out := new(VisualizationAddonsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeConfig) DeepCopyInto(out *VolumeConfig) {
	*out = *in
	in.Volume.DeepCopyInto(&out.Volume)
	in.Mount.DeepCopyInto(&out.Mount)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeConfig.
func (in *VolumeConfig) DeepCopy() *VolumeConfig {
	if in == nil {
		return nil
	}
	out := new(VolumeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZipkinTracerConfig) DeepCopyInto(out *ZipkinTracerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZipkinTracerConfig.
func (in *ZipkinTracerConfig) DeepCopy() *ZipkinTracerConfig {
	if in == nil {
		return nil
	}
	out := new(ZipkinTracerConfig)
	in.DeepCopyInto(out)
	return out
}
