apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  admin-ca: {{ .Values.jaeger.es.certs.ca }}
  admin-cert: {{ .Values.jaeger.es.certs.elasticsearch.admin-cert }}
  admin-key: {{ .Values.jaeger.es.certs.elasticsearch.admin-key }}
  elasticsearch.crt: {{ .Values.jaeger.es.certs.elasticsearch.elasticsearch.crt }}
  elasticsearch.key: {{ .Values.jaeger.es.certs.elasticsearch.elasticsearch.key }}
  logging-es.crt: {{ .Values.jaeger.es.certs.elasticsearch.logging-es.crt }}
  logging-es.key: {{ .Values.jaeger.es.certs.elasticsearch.logging-es.key }}
