apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jaeger-curator
  labels:
    app: elasticsearch
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ca: {{ .Values.jaeger.es.certs.ca }}
  cert: {{ .Values.jaeger.es.certs.curator.cert }}
  key: {{ .Values.jaeger.es.certs.curator.key }}
