apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jaeger-master-certs
  labels:
    app: elasticsearch
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ca: {{ .Values.jaeger.es.certs.ca }}
  ca-key: {{ .Values.jaeger.es.certs.ca-key }}
