{{ if and (eq .Values.provider "jaeger") (eq .Values.jaeger.template "production-elasticsearch") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
  labels:
    app: elasticsearch
    chart: {{ template "tracing.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{ end }}