apiVersion: v1
data:
  auth: ""
kind: Secret
metadata:
  name: prometheus-htpasswd
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    chart: {{ template "prometheus.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
