apiVersion: v1
kind: Service
metadata:
  name: mec
  namespace: {{ .Release.Namespace }}
  labels:
    maistra-version: 2.0.0
    maistra-version: 2.0.0
    app: mec
    chart: {{ template "mec.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: mec
